import {GraduationCap,Eye,LockKeyhole,HeartHandshake,ChevronDown,Users,Briefcase,ArrowUpRight} from 'lucide-react';
import {translator,content,AUTH,RECRUIT,verifiedPartners,verifiedTestimonials,type Locale} from './content';
import {Button,Heading} from './ui';
export function Closing({locale,crmOnly}:{locale:Locale;crmOnly:boolean}){const t=translator(locale),c=content(locale),home='/accueil-public',crm='/crm-centre-formation';
const footerColumns:[string,[string,string][]][]=[
[c.talent,[[c.create,AUTH],[t("Comment ça marche","كيف تعمل المنصة","So funktioniert es","How it works"),home+'#comment-ca-marche'],[t("Les métiers","المهن","Berufsfelder","Career areas"),home+'#metiers']]],
[c.employer,[[c.recruit,RECRUIT],[t("Espace entreprise","فضاء الشركات","Arbeitgeberbereich","Employer area"),'/employeurs']]],
[c.centre,[[t("Solution CRM","حل CRM","CRM-Lösung","CRM solution"),crm],[t("Partenaires","الشركاء","Partner","Partners"),home+'#partenaires']]],
[t("Informations","معلومات","Informationen","Information"),[[t("La plateforme","المنصة","Die Plattform","The platform"),home+'#apercu'],[t("Confiance & données","الثقة والبيانات","Vertrauen & Daten","Trust and data"),home+'#confiance'],[t("Questions fréquentes","الأسئلة الشائعة","Häufige Fragen","Frequently asked questions"),home+'#faq']]]];
return <><section id="partenaires" className="section wrap partner-section"><div className="partner-icon"><GraduationCap size={40}/></div><div><div className="eyebrow">{t("CENTRES PARTENAIRES","المراكز الشريكة","PARTNERZENTREN","PARTNER TRAINING CENTRES")}</div><h2>{t("Construisons des passerelles, ensemble.","لنبنِ جسورًا معًا.","Gemeinsam Brücken bauen.","Let’s build connections together.")}</h2><p>{t("Vous accompagnez des talents au Maroc ? Découvrez comment la solution centres peut soutenir leur parcours.","هل تواكبون المواهب في المغرب؟ اكتشفوا كيف يدعم حل المراكز مسارهم.","Sie begleiten Talente in Marokko? Entdecken Sie, wie die Lösung für Bildungszentren ihren Weg unterstützen kann.","Do you support talent in Morocco? Discover how our training centre solution can support their journey.")}</p>{verifiedPartners.length>0&&<div className="partner-logos">{verifiedPartners.map(p=><a key={p.name} href={p.url}><img src={p.logo} alt={p.name} width="160" height="64" loading="lazy"/></a>)}</div>}</div><Button href={crmOnly?'#fonctionnalites':crm} secondary>{t("Découvrir la solution centres","اكتشاف حل المراكز","Lösung für Bildungszentren entdecken","Explore the training centre solution")}</Button></section>
<section id="confiance" className="section confidence"><div className="wrap"><Heading label={t("UNE RELATION DE CONFIANCE","علاقة مبنية على الثقة","VERTRAUEN ALS GRUNDLAGE","BUILT ON TRUST")} title={t("Votre parcours mérite de la clarté.","مسارك يستحق الوضوح.","Ihr Weg verdient Klarheit.","Your journey deserves clarity.")} center/><div className="three-grid">{[[t("Choisir ce que l’on partage","اختيار ما نشاركه","Bewusst Informationen teilen","Choose what you share"),t("Vérifiez vos réglages et les informations visibles sur votre profil.","راجع إعداداتك والمعلومات الظاهرة في ملفك.","Prüfen Sie Einstellungen und sichtbare Profilinformationen.","Review your settings and the information visible on your profile.")],[t("Partager avec discernement","مشاركة واعية","Informationen bewusst teilen","Share thoughtfully"),t("Consultez les conditions de la plateforme avant de transmettre vos documents.","راجع شروط المنصة قبل إرسال وثائقك.","Lesen Sie die Plattformbedingungen, bevor Sie Dokumente übermitteln.","Read the platform’s terms before sending your documents.")],[t("Comprendre chaque étape","فهم كل خطوة","Jeden Schritt verstehen","Understand each step"),t("Une mise en relation ouvre un échange. Aucun résultat de recrutement n’est garanti.","التواصل يفتح باب الحوار دون ضمان نتيجة التوظيف.","Ein Kontakt eröffnet ein Gespräch, garantiert aber keine Einstellung.","A connection opens a conversation. It does not guarantee a job.")]].map(([title,body],i)=>{const Icon=[Eye,LockKeyhole,HeartHandshake][i];return <article key={title}><Icon size={25}/><h3>{title}</h3><p>{body}</p></article>})}</div></div></section>
{verifiedTestimonials.length>0&&<section className="section wrap"><Heading label={t("TÉMOIGNAGES","تجارب المستخدمين","ERFAHRUNGSBERICHTE","TESTIMONIALS")} title={t("Des parcours racontés par ceux qui les vivent.","مسارات يرويها أصحابها.","Erfahrungen aus erster Hand.","Real experiences, in their own words.")} center/><div className="three-grid">{verifiedTestimonials.map(item=><figure key={item.name}><blockquote>{item.quote[locale]}</blockquote><figcaption>{item.name} · {item.role[locale]}</figcaption></figure>)}</div></section>}
<section id="faq" className="section wrap faq-section"><div><Heading label={t("VOS QUESTIONS, NOS RÉPONSES","أسئلتكم وإجاباتنا","IHRE FRAGEN, UNSERE ANTWORTEN","YOUR QUESTIONS, ANSWERED")} title={t("Avancer, l’esprit clair.","تقدّم برؤية واضحة.","Mit Klarheit weitergehen.","Move forward with clarity.")} description={t("Les repères essentiels pour les talents, les entreprises et les centres.","المعلومات الأساسية للمواهب والشركات والمراكز.","Das Wichtigste für Talente, Unternehmen und Bildungszentren.","Essential information for talent, employers and training centres.")}/><div className="faq-mark" aria-hidden="true">?</div></div><div className="faq-list">{c.faq.map(([q,a])=><details key={q}><summary>{q}<span><ChevronDown size={20}/></span></summary><p>{a}</p></details>)}</div></section>
<section className="final-cta"><div className="wrap"><span className="eyebrow">{t("LE PROCHAIN PAS COMMENCE AVEC VOUS","الخطوة القادمة تبدأ معك","DER NÄCHSTE SCHRITT BEGINNT MIT IHNEN","THE NEXT STEP STARTS WITH YOU")}</span><h2>{t("Et si la suite commençait ici ?","ماذا لو بدأت خطوتك القادمة هنا؟","Was, wenn Ihr nächster Schritt hier beginnt?","What if your next step started here?")}</h2><p>{t("Un talent. Une entreprise. Un centre. Un même horizon.","موهبة. شركة. مركز. وأفق يجمعهم.","Ein Talent. Ein Unternehmen. Ein Bildungszentrum. Ein gemeinsamer Horizont.","Talent. Employers. Training centres. A shared horizon.")}</p><div className="three-grid final-entries">{[[t("Je cherche un emploi","أبحث عن عمل","Ich suche Arbeit","I’m looking for work"),c.create,AUTH],[t("Je suis une entreprise","أمثّل شركة","Ich vertrete ein Unternehmen","I represent a company"),c.recruit,RECRUIT],[t("Je représente un centre","أمثّل مركز تكوين","Ich vertrete ein Bildungszentrum","I represent a training centre"),t("Découvrir le CRM","اكتشاف CRM","CRM entdecken","Explore the CRM"),crm]].map(([title,label,href],i)=>{const Icon=[Users,Briefcase,GraduationCap][i];return <a href={href} key={title}><Icon size={27}/><strong>{title}</strong><span>{label}<ArrowUpRight size={18}/></span></a>})}</div></div></section>
<footer className="footer wrap"><div className="footer-top"><div className="footer-brand"><a className="brand" href={home}><img src="/landing-assets/amud-logo.png" alt="AMUD Skills" width="86" height="86" loading="lazy"/></a><p>{t("Le pont entre les talents au Maroc et les entreprises en Allemagne.","جسر بين المواهب في المغرب والشركات في ألمانيا.","Die Brücke zwischen Talenten in Marokko und Unternehmen in Deutschland.","Connecting talent in Morocco with companies in Germany.")}</p><span>{t("Maroc ↔ Allemagne","المغرب ↔ ألمانيا","Marokko ↔ Deutschland","Morocco ↔ Germany")}</span></div>{footerColumns.map(([title,links])=><div className="footer-column" key={title}><strong>{title}</strong>{links.map(([label,href])=><a key={label} href={href}>{label}</a>)}</div>)}</div><div className="footer-bottom"><span>© {new Date().getFullYear()} AMUD Skills</span><span>{t("Des compétences qui nous rapprochent.","مهارات تقرّب بيننا.","Kompetenzen, die uns verbinden.","Skills that bring us together.")}</span><a href="#main-content">{t("Retour en haut","العودة للأعلى","Nach oben","Back to top")} ↑</a></div></footer></>}
