export type Locale = 'fr'|'ar'|'de'|'en';
export const translator = (locale:Locale) => (fr:string,ar:string,de:string,en:string) => locale==='ar'?ar:locale==='de'?de:locale==='en'?en:fr;
export const AUTH='/auth-phone';
export const RECRUIT=AUTH+'?intent=recruiter';
export const verifiedPartners: {name:string;url:string;logo:string}[]=[];
export const verifiedTestimonials: {name:string;quote:Record<Locale,string>;role:Record<Locale,string>}[]=[];
export function content(locale:Locale){const t=translator(locale);return {
talent:t("Talents","المواهب","Talente","Talent"), employer:t("Entreprises","الشركات","Unternehmen","Companies"), centre:t("Centres de formation","مراكز التكوين","Bildungszentren","Training centres"), create:t("Créer mon profil","إنشاء ملفي المهني","Profil erstellen","Create my profile"),recruit:t("Trouver des talents","البحث عن مواهب","Talente finden","Find talent"),
steps:[
[t("Présentez-vous","عرّف بنفسك","Stellen Sie sich vor","Introduce yourself"),t("Votre métier, votre parcours, vos ambitions.","مهنتك ومسارك وطموحاتك.","Ihr Beruf, Ihr Werdegang, Ihre Ziele.","Your profession, your experience and your ambitions.")],
[t("Valorisez vos compétences","أبرز مهاراتك","Zeigen Sie Ihr Können","Showcase your skills"),t("Ajoutez vos expériences, votre CV et vos diplômes.","أضف خبراتك وسيرتك الذاتية ومؤهلاتك الدراسية.","Ergänzen Sie Ihre Erfahrungen, Ihren Lebenslauf und Ihre Abschlüsse.","Add your experience, CV and qualifications.")],
[t("Présentez-vous en vidéo","قدّم نفسك بالفيديو","Stellen Sie sich im Video vor","Introduce yourself on video"),t("Montrez votre motivation et indiquez votre niveau d’allemand, même débutant.","أبرز دوافعك وحدّد مستواك في الألمانية، حتى لو كنت مبتدئًا.","Zeigen Sie Ihre Motivation und geben Sie Ihr Deutschniveau an – auch als Anfänger.","Share your motivation and indicate your German level, even if you’re a beginner.")],
[t("Ouvrez la conversation","ابدأ التواصل","Beginnen Sie ein Gespräch","Start a conversation"),t("Choisissez votre visibilité et explorez les mises en relation.","حدّد من يمكنه رؤية ملفك واستكشف فرص التواصل.","Legen Sie fest, wer Ihr Profil sehen kann, und entdecken Sie Kontaktmöglichkeiten.","Choose your profile visibility and explore opportunities to connect.")]],
features:[
[t("Un profil qui vous ressemble","ملف يعكس مسارك","Ein Profil, das zu Ihnen passt","A profile that reflects you"),t("Compétences, expériences, CV et diplômes : votre parcours au même endroit.","المهارات والخبرات والسيرة الذاتية والشهادات: مسارك في مكان واحد.","Kompetenzen, Erfahrung, Lebenslauf und Abschlüsse an einem Ort.","Skills, experience, CV and qualifications: your professional background in one place.")],
[t("Une vidéo pour vous présenter","فيديو للتعريف بنفسك","Ein Video, das Sie vorstellt","A video introduction"),t("Parlez de votre parcours et de votre motivation. Présentez-vous en allemand selon votre niveau, lorsque vous êtes prêt.","تحدّث عن مسارك ودوافعك، وقدّم نفسك بالألمانية حسب مستواك عندما تكون مستعدًا.","Erzählen Sie von Ihrem Werdegang und Ihrer Motivation – auf Deutsch passend zu Ihrem Niveau, wenn Sie bereit sind.","Talk about your experience and motivation. Introduce yourself in German at your own level, when you’re ready.")],
[t("Des critères qui comptent","معايير تهمّك","Relevante Kriterien","Criteria that matter"),t("Métier, compétences, expérience et langue pour rapprocher besoins et profils.","المهنة والمهارات والخبرة واللغة لتقريب الاحتياجات من الملفات المناسبة.","Beruf, Fähigkeiten, Erfahrung und Sprache bringen Anforderungen und Profile zusammen.","Profession, skills, experience and language help connect employers’ needs with suitable profiles.")],
[t("Une visibilité choisie","ظهور ملفك باختيارك","Sie bestimmen Ihre Sichtbarkeit","Visibility you choose"),t("Décidez des informations à partager et consultez vos réglages de visibilité.","اختر المعلومات التي تشاركها وراجع إعدادات ظهور ملفك.","Entscheiden Sie, welche Informationen Sie teilen, und prüfen Sie die Sichtbarkeitseinstellungen Ihres Profils.","Choose which information you share and review your profile visibility settings.")],
[t("Une rencontre professionnelle","تواصل مهني","Ein beruflicher Kontakt","A professional connection"),t("Un profil pertinent ouvre la conversation. La décision reste humaine.","الملف المناسب يفتح باب الحوار. ويبقى القرار بيد الأشخاص.","Ein passendes Profil eröffnet das Gespräch. Die Entscheidung treffen Menschen.","A relevant profile opens a conversation. People make the decisions.")],
[t("La formation fait le lien","التكوين يدعم المسار","Bildung verbindet","Training supports your journey"),t("Les centres accompagnent les apprenants et structurent leur suivi.","تواكب المراكز المتعلمين وتنظم متابعة مسارهم.","Bildungszentren begleiten Lernende und dokumentieren ihre Fortschritte.","Training centres support learners and organise their progress tracking.")]],
crmFeatures:[
[t("Apprenants & inscriptions","المتعلمون والتسجيلات","Lernende & Anmeldungen","Learners and enrolments"),t("Rassemblez les dossiers et suivez les inscriptions.","اجمع الملفات وتابع التسجيلات.","Bündeln Sie die Unterlagen und behalten Sie Anmeldungen im Blick.","Bring records together and track enrolments.")],
[t("Enseignants & groupes","الأساتذة والمجموعات","Lehrkräfte & Gruppen","Teachers and groups"),t("Organisez les équipes, formations et groupes.","نظّم الفرق والتكوينات والمجموعات.","Organisieren Sie Teams, Kurse und Gruppen.","Organise teams, courses and groups.")],
[t("Planning des cours","جدولة الدروس","Kursplanung","Class scheduling"),t("Coordonnez les séances et les disponibilités.","نسّق الحصص وأوقات التوفر.","Koordinieren Sie Unterrichtstermine und Verfügbarkeiten.","Coordinate lessons and availability.")],
[t("Présences par QR","الحضور برمز QR","Anwesenheit per QR-Code","QR code attendance"),t("Simplifiez le pointage et le suivi des absences.","بسّط تسجيل الحضور وتتبع الغياب.","Vereinfachen Sie die Anwesenheitserfassung und die Übersicht über Fehlzeiten.","Simplify attendance recording and absence tracking.")],
[t("Paiements & rémunérations","المدفوعات والأجور","Zahlungen & Vergütung","Payments and remuneration"),t("Suivez les échéances et les règlements.","تابع مواعيد الاستحقاق والمدفوعات.","Behalten Sie Fälligkeiten und Zahlungen im Blick.","Track due dates and payments.")],
[t("Suivi pédagogique","المتابعة التربوية","Lernbegleitung","Learning support and progress"),t("Gardez une vue claire sur la progression.","تابع تقدّم المتعلمين بوضوح.","Behalten Sie die Fortschritte der Lernenden im Blick.","Keep a clear view of learners’ progress.")]],
faq:[
[t("Faut-il déjà parler allemand ?","هل يجب أن أتحدث الألمانية مسبقًا؟","Muss ich bereits Deutsch sprechen?","Do I need to speak German already?"),t("Non. Vous pouvez commencer votre profil sans allemand. Les exigences linguistiques varient selon le métier et l’entreprise ; renseigner votre niveau aide à mieux situer votre parcours.","لا. يمكنك إنشاء ملفك دون معرفة الألمانية. تختلف متطلبات اللغة حسب المهنة والشركة، وتحديد مستواك يساعد على توضيح مسارك.","Nein. Sie können Ihr Profil ohne Deutschkenntnisse beginnen. Die Sprachanforderungen hängen von Beruf und Unternehmen ab. Ihr aktuelles Niveau hilft, Ihren Weg einzuordnen.","No. You can start your profile without knowing German. Language requirements vary by profession and company. Stating your current level helps employers understand where you are in your journey.")],
[t("À qui s’adresse AMUD Skills ?","لمن توجّه AMUD Skills خدماتها؟","Für wen ist AMUD Skills gedacht?","Who is AMUD Skills for?"),t("Aux diplômés, stagiaires et professionnels au Maroc, aux entreprises en Allemagne et aux centres de formation qui accompagnent les apprenants.","للخريجين والمتدربين والمهنيين في المغرب، وللشركات في ألمانيا، ولمراكز التكوين التي تواكب المتعلمين.","Für Absolventen, Praktikanten und Berufstätige in Marokko, Unternehmen in Deutschland und Bildungszentren, die Lernende begleiten.","Graduates, trainees and professionals in Morocco, companies in Germany, and training centres that support learners.")],
[t("Comment rechercher des talents ?","كيف تبحث الشركة عن المواهب؟","Wie finden Unternehmen Talente?","How can companies find talent?"),t("Depuis l’espace recruteur, précisez vos besoins, examinez les compétences, l’expérience et le niveau de langue renseignés, puis engagez la mise en relation.","حدّدوا احتياجاتكم في فضاء المشغّلين، وراجعوا المهارات والخبرة ومستوى اللغة المذكور في الملفات، ثم ابدؤوا التواصل.","Definieren Sie im Arbeitgeberbereich Ihren Bedarf, prüfen Sie Kompetenzen, Erfahrung und angegebene Sprachkenntnisse und kontaktieren Sie passende Profile.","In the employer area, describe your needs, review the skills, experience and language levels listed, then start a conversation.")],
[t("Qui peut voir mon profil et mes documents ?","من يمكنه رؤية ملفي ووثائقي؟","Wer sieht mein Profil und meine Dokumente?","Who can see my profile and documents?"),t("La visibilité dépend des réglages de votre compte et des accès accordés dans la plateforme. Vérifiez ces paramètres avant de publier votre profil ou de partager un document.","يتوقف الظهور على إعدادات حسابك والصلاحيات الممنوحة داخل المنصة. راجعها قبل نشر ملفك أو مشاركة وثيقة.","Die Sichtbarkeit hängt von Ihren Kontoeinstellungen und den Zugriffsrechten der Plattform ab. Prüfen Sie diese vor der Veröffentlichung oder dem Teilen von Dokumenten.","Visibility depends on your account settings and the access permissions granted on the platform. Check these before publishing your profile or sharing a document.")],
[t("La mise en relation garantit-elle un emploi ?","هل يضمن التواصل الحصول على وظيفة؟","Garantiert ein Kontakt eine Arbeitsstelle?","Does connecting with an employer guarantee a job?"),t("Non. AMUD Skills facilite l’identification et le contact. Les échanges, la sélection et les suites du parcours dépendent des candidats, des employeurs et des exigences applicables.","لا. تسهّل AMUD Skills العثور على الملفات والتواصل مع أصحابها. وتعتمد المحادثات والاختيار والخطوات اللاحقة على المرشحين والمشغّلين والمتطلبات المعمول بها.","Nein. AMUD Skills erleichtert die Suche und die Kontaktaufnahme. Gespräche, Auswahl und weitere Schritte hängen von Bewerbenden, Arbeitgebern und den geltenden Anforderungen ab.","No. AMUD Skills helps people find and contact each other. Conversations, selection and subsequent steps depend on candidates, employers and the applicable requirements.")],
[t("Quels sont les tarifs ?","ما هي الأسعار؟","Welche Kosten entstehen?","What does it cost?"),t("Consultez les conditions affichées dans votre espace avant de vous engager. Pour les centres, les modalités sont à confirmer avec l’équipe AMUD Skills selon vos besoins.","راجع الشروط المعروضة في فضائك قبل الالتزام. بالنسبة للمراكز، تحدّد التفاصيل مع فريق AMUD Skills حسب الاحتياجات.","Prüfen Sie die Bedingungen in Ihrem Bereich, bevor Sie sich entscheiden. Bildungszentren klären die Konditionen entsprechend ihrem Bedarf mit dem AMUD Skills Team.","Review the terms shown in your account before committing. Training centres should confirm the arrangements with the AMUD Skills team based on their needs.")],
[t("Que comprend la solution pour les centres ?","ماذا يتضمن حل مراكز التكوين؟","Was bietet die Lösung für Bildungszentren?","What does the training centre solution include?"),t("Étudiants, enseignants, formations, groupes, planning, présences QR, paiements et suivi pédagogique. La page dédiée présente ces usages en détail.","إدارة المتعلمين والأساتذة والتكوينات والمجموعات وجدولة الدروس والحضور برمز QR والمدفوعات والمتابعة التربوية. تعرض الصفحة المخصصة هذه الاستخدامات بالتفصيل.","Verwaltung von Lernenden, Lehrkräften, Kursen, Gruppen, Terminen, QR-Code-Anwesenheit und Zahlungen sowie Lernbegleitung. Die zugehörige Seite erläutert diese Funktionen.","Learners, teachers, courses, groups, scheduling, QR code attendance, payments and learning support. The dedicated page explains these uses in more detail.")]]
};}
