'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight,ChevronLeft,ChevronRight,Pause,Play} from 'lucide-react';
import {Carousel,CarouselContent,CarouselItem,type CarouselApi} from './primitives/carousel';
import {AnimatedFrame,useSiteMotion} from './motion';
import {translator,type Locale} from './content';

type Slide={src:string;alt:string;title?:string;eyebrow?:string;subtitle?:string;href?:string;position?:string;width:number;height:number};
export function PhotoSlider({locale,slides,variant='careers'}:{locale:Locale;slides:Slide[];variant?:'hero'|'careers'}){
 const t=translator(locale),rtl=locale==='ar',motion=useSiteMotion();
 const [api,setApi]=useState<CarouselApi>(),[selected,setSelected]=useState(0),[paused,setPaused]=useState(false),[hovering,setHovering]=useState(false),[inView,setInView]=useState(false),[focused,setFocused]=useState(false);
 const host=useRef<HTMLDivElement>(null),[canAnimate,setCanAnimate]=useState(false);
 const running=motion&&!paused&&!hovering&&!focused&&inView;
 useEffect(()=>{setCanAnimate(motion);},[motion]);
 useEffect(()=>{if(!api)return;const sync=()=>setSelected(api.selectedScrollSnap());sync();api.on('select',sync);api.on('reInit',sync);const stop=()=>setPaused(true),release=()=>{if(variant==='hero')setPaused(false);};api.on('pointerDown',stop);api.on('pointerUp',release);return()=>{api.off('select',sync);api.off('reInit',sync);api.off('pointerDown',stop);api.off('pointerUp',release);};},[api,variant]);
 useEffect(()=>{const observer=new IntersectionObserver(([entry])=>setInView(entry.isIntersecting),{threshold:.3});if(host.current)observer.observe(host.current);return()=>observer.disconnect();},[]);
 useEffect(()=>{if(!running||!api)return;const timer=window.setInterval(()=>api.scrollTo((api.selectedScrollSnap()+1)%slides.length),6500);return()=>clearInterval(timer);},[running,api,slides.length,selected]);
 const go=(index:number)=>{if(variant!=='hero')setPaused(true);api?.scrollTo((index+slides.length)%slides.length,!canAnimate);};
 return <div ref={host} className={'photo-slider '+variant+'-slider'} onMouseEnter={()=>setHovering(true)} onMouseLeave={()=>setHovering(false)} onFocusCapture={event=>{if(variant==='hero')setFocused(true);else if(!(event.target as Element).closest('.slider-play'))setPaused(true);}} onBlurCapture={event=>{if(!event.currentTarget.contains(event.relatedTarget as Node|null))setFocused(false);}}>
 <Carousel setApi={setApi} opts={{direction:rtl?'rtl':'ltr',align:'start',loop:variant==='hero',duration:canAnimate?30:0}} aria-label={variant==='hero'?t("Les talents en images","المواهب بالصور","Talente in Bildern","Talent in pictures"):t("Découvrir les métiers en images","اكتشاف المهن بالصور","Berufsfelder in Bildern","Explore careers in pictures")} aria-roledescription={t("diaporama","عارض شرائح","Diashow","slideshow")} onKeyDownCapture={event=>{
  if(event.key==='ArrowLeft'||event.key==='ArrowRight'){event.preventDefault();go(selected+((event.key==='ArrowRight')!==rtl?1:-1));}
  if(event.key==='Home'){event.preventDefault();go(0);}if(event.key==='End'){event.preventDefault();go(slides.length-1);}
 }}>
 <AnimatedFrame variant={variant==='hero'?'hero':'card'}><CarouselContent className="photo-track">{slides.map((slide,index)=><CarouselItem key={slide.src} className="photo-slide" aria-label={`${index+1} / ${slides.length}`} aria-roledescription={t("diapositive","شريحة","Folie","slide")} aria-hidden={selected!==index} inert={selected!==index}>
 {variant==='careers'?<CareerPhoto slide={slide}/>:<img className="hero-photo" style={slide.position?{objectPosition:slide.position}:undefined} src={slide.src} alt={slide.alt} width={slide.width} height={slide.height} loading={index===0?'eager':'lazy'} fetchPriority={index===0?'high':undefined} draggable={false}/>}

 </CarouselItem>)}</CarouselContent></AnimatedFrame>
 <div className="slider-controls">{variant!=='hero'&&<button type="button" onClick={()=>go(selected-1)} aria-label={t("Image précédente","الصورة السابقة","Vorheriges Bild","Previous image")}>{rtl?<ChevronRight size={19}/>:<ChevronLeft size={19}/>}</button>}<div className="slider-dots">{slides.map((slide,index)=><button type="button" key={slide.src} onClick={()=>go(index)} aria-label={t("Afficher l’image","عرض الصورة","Bild anzeigen","Show image")+' '+(slide.title||index+1)} aria-current={selected===index?'true':undefined}><span/></button>)}</div>{variant==='hero'?<span className="hero-slide-name">{slides[selected].title}</span>:<><button type="button" onClick={()=>go(selected+1)} aria-label={t("Image suivante","الصورة التالية","Nächstes Bild","Next image")}>{rtl?<ChevronLeft size={19}/>:<ChevronRight size={19}/>}</button><button className="slider-play" type="button" disabled={!motion} onClick={()=>setPaused(value=>!value)} aria-label={!motion?t("Animations désactivées","الحركات متوقفة","Animationen deaktiviert","Animations disabled"):paused?t("Lancer le défilement automatique","تشغيل العرض التلقائي","Automatischen Wechsel starten","Start automatic slideshow"):t("Arrêter le défilement automatique","إيقاف العرض التلقائي","Automatischen Wechsel pausieren","Pause automatic slideshow")} aria-pressed={!paused&&motion}>{paused||!motion?<Play size={15}/>:<Pause size={15}/>}</button></>}</div>
 <span className="sr-only" aria-live={running?'off':'polite'} aria-atomic="true">{t("Image","الصورة","Bild","Image")} {selected+1} / {slides.length}</span>
 </Carousel></div>;
}

export function HeroSlider({locale}:{locale:Locale}){
 const t=translator(locale);
 const careers=careerSlides(locale).map((slide,index)=>({...slide,title:slide.eyebrow,position:['54% center','47% center','54% center','45% center','48% center','53% center'][index]}));
 return <PhotoSlider key="automotive-first" locale={locale} variant="hero" slides={[
 ...[5,3,4,2,1,0].map(index=>careers[index]),
 {src:'/landing-assets/careers/chef-morocco.webp',title:t("Cuisine & restauration","الطبخ والمطاعم","Küche & Gastronomie","Cooking and hospitality"),alt:t("Illustration générée par IA : un jeune chef marocain prépare un plat en cuisine professionnelle","صورة مولّدة بالذكاء الاصطناعي لطاهٍ مغربي شاب يجهّز طبقًا في مطبخ مهني","KI-generiertes Symbolbild: junger marokkanischer Koch richtet ein Gericht in einer Profiküche an","AI-generated illustration: a young Moroccan chef prepares a dish in a professional kitchen"),width:1440,height:960,position:'52% center'},
 {src:'/landing-assets/careers/server-technician-morocco.webp',title:t("Technique & industrie","التقنية والصناعة","Technik & Industrie","Technology and industry"),alt:t("Illustration générée par IA : une technicienne marocaine contrôle les connexions de commutateurs réseau dans une salle de serveurs","صورة مولّدة بالذكاء الاصطناعي لتقنية مغربية تفحص توصيلات محوّلات الشبكة في غرفة خوادم","KI-generiertes Symbolbild: marokkanische Technikerin prüft Netzwerk-Switches in einem Serverraum","AI-generated illustration: a Moroccan technician checks network switch connections in a server room"),width:1440,height:960,position:'58% center'}
 ]}/>;
}
function CareerPhoto({slide}:{slide:Slide}){const Tag=slide.href?'a':'div';return <Tag href={slide.href} className="career-photo"><img src={slide.src} alt={slide.alt} width={slide.width} height={slide.height} loading="lazy" draggable={false}/><div><small>{slide.eyebrow}</small><h3>{slide.title}</h3><span>{slide.subtitle}{slide.href&&<ArrowUpRight/>}</span></div></Tag>;}
export function CareersSlider({locale}:{locale:Locale}){return <PhotoSlider locale={locale} slides={careerSlides(locale)}/>;}
function careerSlides(locale:Locale):Slide[]{const t=translator(locale);return [
 {src:'/landing-assets/careers/logistics.webp',width:1440,height:720,eyebrow:t("LOGISTIQUE","اللوجستيك","LOGISTIK","LOGISTICS"),title:t("Chaque geste fait avancer.","كل خطوة تدفع العمل للأمام.","Jeder Handgriff bewegt etwas.","Every task keeps things moving."),subtitle:t("Préparation · Organisation · Expédition","التحضير · التنظيم · الشحن","Vorbereitung · Organisation · Versand","Preparation · Organisation · Shipping"),alt:t("Illustration générée par IA : un jeune professionnel marocain prépare des colis dans un entrepôt","صورة مولّدة بالذكاء الاصطناعي لشاب مغربي يحضّر الطرود في مستودع","KI-generiertes Symbolbild: junger marokkanischer Mitarbeiter bereitet Pakete im Lager vor","AI-generated illustration: a young Moroccan professional prepares parcels in a warehouse")},
 {src:'/landing-assets/careers/nurses.webp',width:1440,height:960,eyebrow:t("SOINS & SANTÉ","التمريض والصحة","PFLEGE & GESUNDHEIT","NURSING AND HEALTHCARE"),title:t("Le soin commence par l’attention.","العناية تبدأ بالاهتمام.","Fürsorge beginnt mit Aufmerksamkeit.","Care starts with attention."),subtitle:t("Soins infirmiers · Équipe · Attention","التمريض · التعاون · العناية","Pflege · Teamarbeit · Zuwendung","Nursing · Teamwork · Care"),alt:t("Illustration générée par IA : deux jeunes infirmières marocaines préparent du matériel de soins","صورة مولّدة بالذكاء الاصطناعي لممرضتين مغربيتين تجهزان مستلزمات الرعاية","KI-generiertes Symbolbild: zwei junge marokkanische Pflegekräfte bereiten Pflegematerial vor","AI-generated illustration: two young Moroccan nurses prepare care supplies")},
 {src:'/landing-assets/careers/truck-driver.webp',width:1440,height:581,eyebrow:t("TRANSPORT ROUTIER","قيادة الشاحنات","GÜTERVERKEHR","ROAD FREIGHT"),title:t("Des compétences qui vont loin.","مهارات تقطع مسافات.","Kompetenzen, die Sie weiterbringen.","Skills that take you further."),subtitle:t("Poids lourds · Rigueur · Responsabilité","الشاحنات · الدقة · المسؤولية","Lkw · Sorgfalt · Verantwortung","Trucks · Precision · Responsibility"),alt:t("Illustration générée par IA : un jeune conducteur marocain près de son camion à l’arrêt","صورة مولّدة بالذكاء الاصطناعي لسائق مغربي شاب قرب شاحنته المتوقفة","KI-generiertes Symbolbild: junger marokkanischer Fahrer neben einem geparkten Lkw","AI-generated illustration: a young Moroccan driver beside his parked truck")},
 {src:'/landing-assets/careers/bus-driver.webp',width:1440,height:960,eyebrow:t("TRANSPORT DE VOYAGEURS","قيادة الحافلات","PERSONENVERKEHR","PASSENGER TRANSPORT"),title:t("Relier les personnes, chaque jour.","نربط بين الناس كل يوم.","Menschen verbinden. Jeden Tag.","Connecting people, every day."),subtitle:t("Autobus · Accueil · Vigilance","الحافلات · الاستقبال · اليقظة","Bus · Fahrgastkontakt · Aufmerksamkeit","Buses · Passenger service · Awareness"),alt:t("Illustration générée par IA : un jeune conducteur marocain au poste de conduite d’un autobus à l’arrêt","صورة مولّدة بالذكاء الاصطناعي لسائق مغربي شاب في مقعد قيادة حافلة متوقفة","KI-generiertes Symbolbild: junger marokkanischer Fahrer am Steuer eines stehenden Busses","AI-generated illustration: a young Moroccan driver at the wheel of a stationary bus")},
 {src:'/landing-assets/careers/mechanic.webp',width:1440,height:720,eyebrow:t("MÉCANIQUE","الميكانيك","MECHANIK","MECHANICS"),title:t("Comprendre. Réparer. Faire durer.","نفهم. نصلح. نطيل عمر المعدات.","Verstehen. Reparieren. Erhalten.","Understand. Repair. Make it last."),subtitle:t("Diagnostic · Entretien · Précision","التشخيص · الصيانة · الدقة","Diagnose · Wartung · Präzision","Diagnostics · Maintenance · Precision"),alt:t("Illustration générée par IA : un jeune mécanicien marocain examine un moteur en atelier","صورة مولّدة بالذكاء الاصطناعي لميكانيكي مغربي شاب يفحص محركًا في ورشة","KI-generiertes Symbolbild: junger marokkanischer Mechaniker untersucht einen Motor in der Werkstatt","AI-generated illustration: a young Moroccan mechanic inspects an engine in a workshop")},
 {src:'/landing-assets/careers/automotive-worker.webp',width:1440,height:720,eyebrow:t("INDUSTRIE AUTOMOBILE","صناعة السيارات","AUTOMOBILINDUSTRIE","AUTOMOTIVE MANUFACTURING"),title:t("Le savoir-faire prend forme.","مهارة تتحول إلى إنجاز.","Können nimmt Gestalt an.","Skills take shape."),subtitle:t("Assemblage · Qualité · Travail d’équipe","التجميع · الجودة · العمل الجماعي","Montage · Qualität · Teamarbeit","Assembly · Quality · Teamwork"),alt:t("Illustration générée par IA : une jeune opératrice marocaine assemble une pièce automobile à son poste","صورة مولّدة بالذكاء الاصطناعي لعاملة مغربية شابة تجمع قطعة في مصنع سيارات","KI-generiertes Symbolbild: junge marokkanische Mitarbeiterin montiert ein Bauteil in der Fahrzeugfertigung","AI-generated illustration: a young Moroccan worker assembles an automotive component at her workstation")}
 ];}
