<?php
namespace App\Http\Controllers\Api;
use App\Http\Controllers\Controller;use App\Models\AdminActivityLog;use App\Models\JobApplication;use App\Models\JobOffer;use App\Models\AppNotification;use Illuminate\Database\Eloquent\Builder;use Illuminate\Http\JsonResponse;use Illuminate\Http\Request;
class AdminMarketplaceController extends Controller{
 public function offers(Request $r):JsonResponse{$d=$r->validate(['q'=>'sometimes|string|max:100','status'=>'sometimes|in:draft,published,closed','user_id'=>'sometimes|integer|exists:users,id','per_page'=>'sometimes|integer|min:5|max:100']);$q=JobOffer::with('employer.companyProfile')->withCount('applications');if(!empty($d['q'])){$s=$d['q'];$q->where(fn(Builder $b)=>$b->where('title','like',"%$s%")->orWhere('city','like',"%$s%")->orWhere('sector','like',"%$s%"));}foreach(['status','user_id'] as $f)if(isset($d[$f]))$q->where($f,$d[$f]);return response()->json($q->latest()->paginate($d['per_page']??20));}
 public function updateOffer(Request $r,JobOffer $offer):JsonResponse{$d=$r->validate(['status'=>'required|in:draft,published,closed','reason'=>'required_if:status,draft,closed|nullable|string|max:1000']);$before=$offer->status;$offer->update(['status'=>$d['status'],'published_at'=>$d['status']==='published'?($offer->published_at??now()):$offer->published_at]);AdminActivityLog::record($r->user(),$offer,'offer_status_changed',['from'=>$before,'to'=>$d['status'],'reason'=>$d['reason']??null]);AppNotification::create(['user_id'=>$offer->user_id,'type'=>'offer.moderated','title'=>'Offer status updated','body'=>$d['status'],'link'=>"/recruiter/offers/{$offer->id}"]);return response()->json($offer);}
 public function applications(Request $r):JsonResponse{$d=$r->validate(['status'=>'sometimes|in:submitted,viewed,interview,accepted,rejected,withdrawn','offer_id'=>'sometimes|integer|exists:job_offers,id','per_page'=>'sometimes|integer|min:5|max:100']);$q=JobApplication::with(['offer.employer.companyProfile','candidateProfile.user']);foreach(['status','offer_id'] as $f)if(isset($d[$f]))$q->where($f,$d[$f]);return response()->json($q->latest('applied_at')->paginate($d['per_page']??20));}
 public function activity(Request $r):JsonResponse{$d=$r->validate(['action'=>'sometimes|string|max:100','actor_id'=>'sometimes|integer|exists:users,id','per_page'=>'sometimes|integer|min:5|max:100']);$q=AdminActivityLog::with('actor:id,name,phone');foreach(['action','actor_id'] as $f)if(isset($d[$f]))$q->where($f,$d[$f]);return response()->json($q->latest()->paginate($d['per_page']??50));}
}
