<?php
namespace App\Http\Controllers\Api;
use App\Http\Controllers\Controller; use App\Models\AppNotification; use App\Models\JobApplication; use App\Models\JobOffer; use App\Services\CandidateProfileResolver; use App\Services\RecruiterCandidateSearch; use Illuminate\Http\JsonResponse; use Illuminate\Http\Request;
class CandidateApplicationController extends Controller {
 public function recruiterIndex(Request $r):JsonResponse{$d=$r->validate(['status'=>'sometimes|in:submitted,viewed,interview,accepted,rejected,withdrawn','offer_id'=>'sometimes|integer','per_page'=>'sometimes|integer|min:5|max:100']);$q=JobApplication::whereHas('offer',fn($x)=>$x->where('user_id',$r->user()->id))->with(['offer','candidateProfile.user','candidateProfile.languages']);foreach(['status','offer_id'] as $f)if(isset($d[$f]))$q->where($f,$d[$f]);return response()->json($q->latest('applied_at')->paginate($d['per_page']??20));}
 public function index(Request $r):JsonResponse{$p=CandidateProfileResolver::resolve($r->user());return response()->json($p->jobApplications()->with('offer.employer.companyProfile')->latest('applied_at')->paginate(min(100,max(1,$r->integer('per_page',20)))));}
 public function apply(Request $r,JobOffer $offer):JsonResponse{$p=CandidateProfileResolver::resolve($r->user());abort_unless($offer->status==='published',404);abort_unless($p->submitted_at,422,'Submit your candidate profile before applying.');if($offer->required_cefr_level){$ok=$p->languages()->whereIn('cefr_level',RecruiterCandidateSearch::levelsAtLeast($offer->required_cefr_level))->exists();abort_unless($ok,422,'Required CEFR level not met.');}$a=JobApplication::firstOrCreate(['candidate_profile_id'=>$p->id,'job_offer_id'=>$offer->id],['status'=>'submitted','applied_at'=>now(),'status_changed_at'=>now()]);abort_unless($a->wasRecentlyCreated,409,'You already applied to this offer.');AppNotification::create(['user_id'=>$offer->user_id,'type'=>'application.created','title'=>'New application','body'=>$offer->title,'link'=>"/recruiter/offers/{$offer->id}/applications"]);return response()->json($a->load('offer'),201);}
 public function withdraw(Request $r,JobApplication $application):JsonResponse{$p=CandidateProfileResolver::resolve($r->user());abort_unless($application->candidate_profile_id===$p->id,403);abort_if(in_array($application->status,['accepted','rejected','withdrawn'],true),409);$application->update(['status'=>'withdrawn','withdrawn_at'=>now(),'status_changed_at'=>now()]);return response()->json($application);}
 public function updateStatus(Request $r,JobApplication $application):JsonResponse{abort_unless($application->offer->user_id===$r->user()->id,403);$d=$r->validate(['status'=>'required|in:viewed,interview,accepted,rejected']);$application->update(['status'=>$d['status'],'status_changed_at'=>now()]);AppNotification::create(['user_id'=>$application->candidateProfile->user_id,'type'=>'application.status','title'=>'Application updated','body'=>$d['status'],'link'=>'/candidatures']);return response()->json($application);}
}
