<?php
namespace App\Http\Controllers\Api;
use App\Http\Controllers\Controller; use App\Models\JobOffer; use Illuminate\Database\Eloquent\Builder; use Illuminate\Http\JsonResponse; use Illuminate\Http\Request;
class JobOfferController extends Controller {
 public function mine(Request $r): JsonResponse { $this->company($r); $d=$r->validate(['status'=>'sometimes|in:draft,published,closed','per_page'=>'sometimes|integer|min:5|max:100']);$q=JobOffer::where('user_id',$r->user()->id)->withCount('applications');if(isset($d['status']))$q->where('status',$d['status']);return response()->json($q->latest()->paginate($d['per_page']??20)); }
 public function index(Request $r): JsonResponse { $q=JobOffer::with('employer.companyProfile')->where('status','published')->whereNotNull('published_at')->where('published_at','<=',now()); foreach(['sector','city','contract_type','required_cefr_level'] as $f) if($r->filled($f))$q->where($f,$r->string($f)); if($r->filled('q')){$s=$r->string('q');$q->where(fn(Builder $b)=>$b->where('title','like',"%$s%")->orWhere('description','like',"%$s%"));} return response()->json($q->latest('published_at')->paginate(min(100,max(1,$r->integer('per_page',20))))); }
 public function show(JobOffer $offer): JsonResponse { abort_unless($offer->status==='published'&&$offer->published_at?->isPast(),404); return response()->json($offer->load('employer.companyProfile')); }
 public function store(Request $r): JsonResponse { $this->company($r); $d=$this->validated($r); $d['user_id']=$r->user()->id; if(($d['status']??'draft')==='published')$d['published_at']??=now(); return response()->json(JobOffer::create($d),201); }
 public function update(Request $r,JobOffer $offer): JsonResponse { $this->owns($r,$offer);$d=$this->validated($r,true);if(($d['status']??null)==='published'&&!$offer->published_at)$d['published_at']=now();$offer->update($d);return response()->json($offer->fresh()); }
 public function destroy(Request $r,JobOffer $offer): JsonResponse {$this->owns($r,$offer);abort_if($offer->applications()->exists(),409,'An offer with applications cannot be deleted.');$offer->delete();return response()->json([],204);}
 private function company(Request $r): void {abort_unless($r->user()->hasRole('Company'),403);} private function owns(Request $r,JobOffer $o):void{$this->company($r);abort_unless($o->user_id===$r->user()->id,403);}
 private function validated(Request $r,bool $partial=false):array{$p=$partial?'sometimes':'required';return $r->validate(['title'=>[$p,'string','max:255'],'description'=>[$p,'string'],'sector'=>[$p,'string','max:100'],'city'=>[$p,'string','max:100'],'country'=>['sometimes','string','max:100'],'required_cefr_level'=>['nullable','in:A1,A2,B1,B2,C1,C2'],'salary_min'=>['nullable','integer','min:0'],'salary_max'=>['nullable','integer','gte:salary_min'],'currency'=>['sometimes','string','size:3'],'contract_type'=>[$p,'in:permanent,fixed_term,apprenticeship,temporary,internship'],'status'=>['sometimes','in:draft,published,closed'],'published_at'=>['nullable','date']]);}
}
